log_level = "warn"
outputs = { Targets = ["DP-1"] }
position = "Top"
app_launcher_cmd = "wofi -show drun"

[modules]
left = [ [ "appLauncher", "Workspaces" ] ]
center = [ "Tray"]
right = [ ["Clock", "Privacy", "Settings", "Notifications"] ]

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "rofi -show drun"

[[CustomModule]]
name = "Notifications"
icon = "󰍥"
command = "swaync-client --toggle-panel"

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
style = "Solid"

primary_color = "#8caaee"
success_color = "#8caaee"
text_color = "#c6d0f5"
workspace_colors = [ "#8caaee", "#8caaee" ]
special_workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#8caaee"
weak = "#e5c890"

[appearance.background_color]
base = "#303446"
weak = "#292c3c"
strong = "#232634"

[appearance.secondary_color]
base = "#303446"
